
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
labels:
  name: datadog
  env: prod

spec:
  project: datadog-operatorv3
  source:
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.59.3
    chart: datadog
    helm:
      releaseName: datadog
      values: |
        datadog:
          apiKeyExistingSecret: datadog-secret
          appKeyExistingSecret: datadog-secret
          site: datadoghq.com
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
    - Validate=false
    - CreateNamespace=true
